spring.application.name=frontend

# Config puerto
server.port=8086

auth.api.url=${AUTH_URL}
agregador.api.url=${AGREGADOR_URL}
dinamica.api.url=${DINAMICA_URL}
estadisticas.api.url=${ESTADISTICAS_URL}

spring.mvc.hiddenmethod.filter.enabled=true

spring.thymeleaf.enable-spring-el-compiler=true

logging.level.org.springframework.web.reactive.function.client=DEBUG
logging.level.reactor.netty.http.client=DEBUG