spring.config.activate.on-profile=dev

spring.application.name=frontend

# Config puerto
server.port=8086

auth.api.url=http://localhost:8087/api
agregador.api.url=http://localhost:8081/api
dinamica.api.url=http://localhost:8080/api/dinamica
estadisticas.api.url=http://localhost:8085/api/estadisticas

spring.mvc.hiddenmethod.filter.enabled=true

logging.level.org.springframework.web.reactive.function.client=DEBUG
logging.level.reactor.netty.http.client=DEBUG



management.endpoint.health.show-details=Always