spring.application.name=fuenteEstatica

# Config puerto
server.port=8082

##Configuración de S3
s3.access.key=${ACCESS_KEY}
s3.secret.key=${SECRET_KEY}
s3.bucket.name=${BUCKET_NAME}

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration