spring.application.name=FuenteDinamica
# Config puerto
server.port=8080

auth.api.url=${AUTH_API:http://localhost:8087/api}

# Muestra los logs de tu paquete específico
logging.level.ar.utn.ba.ddsi.fuenteDinamica=DEBUG

# O para ver todos los logs de tu aplicación, incluyendo los de frameworks
# logging.level.root=DEBUG

##Configuración de la Base de Datos
spring.datasource.url=${DISENO_DB_URL}
spring.datasource.username=${DISENO_DB_USERNAME}
spring.datasource.password=${DISENO_DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

##Configuración de Sincronización de entities con la base de datos
spring.jpa.hibernate.ddl-auto=update
# none: no toca la bd
# validate: valida que las entidades coincidan con la bd
# update: actualiza la BD segun las entidades (muy usado en desarrollo)
# create: crea las tablas en cada inicio
# create-drop: igual que create pero borra al apagar

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
