spring.config.activate.on-profile=prod

spring.application.name=ProdServicioAutenticacion

# Server port
server.port=8087

# Application logs
logging.level.ar.utn.ba.ddsi.servicioAutenticacion=DEBUG
# logging.level.root=DEBUG

## Database configuration
spring.datasource.url=${DISENO_DB_URL}
spring.datasource.username=${DISENO_DB_USERNAME}
spring.datasource.password=${DISENO_DB_URL}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

## Hibernate configuration
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

management.endpoint.health.show-details=never
spring.main.banner-mode=off
